### ISSUE TITLE
client.socket not initialised

### ISSUE THREAD

**Issue by gautam-dev-maker** [SAtacker/cpp_chat#1]
on this line https://github.com/SAtacker/cpp_chat/blob/e91e4dfd75830ce8755b2477792c334169cea1fe/include/libmain/chat.hpp#L14

client socket is not initialised.

**Comment by SAtacker** [comment]
This issue is now solved in [commit](https://github.com/SAtacker/cpp_chat/commit/6cb99f3529b2425cbe456c997caaf04db530e0b9)
